### ISSUE TITLE
404 URL when loading the website

### ISSUE THREAD

**Issue by fabianpiau** [ExpediaGroup/expediagroup.github.io#24]
The website tries to load the URL: https://expediagroup.github.io/null

<img width="450" alt="image" src="https://user-images.githubusercontent.com/6502229/122958380-b3be5c00-d37a-11eb-94d3-2142495a7f7f.png">

**Comment by giorgiodg** [comment]
It seems related to the 3rd party widget used to fetch Medium posts
<img width="1775" alt="image" src="https://user-images.githubusercontent.com/1042421/124945884-dbfeb980-e00e-11eb-8b45-46e87f49d035.png">

**Comment by ffeltrinelli** [comment]
Thanks for reporting, this was a bug in the 3rd party widget we use to show Medium posts, it caused this null when a blog's author had not set a profile picture. Since then, this bug seems to have been fixed so I'm closing this issue.
