### ISSUE TITLE
Find alternative source for Medium posts

### ISSUE THREAD

**Issue by ffeltrinelli** [ExpediaGroup/expediagroup.github.io#37]
We are currently using [Pixel Point's Medium widget](https://medium-widget.pixelpoint.io/) to show Medium posts. This widget is very nice and easy to use, but unfortunately it doesn't seem to have an official support channel. Recently it went down for some hours and we didn't have a way to know whether the owners were aware of the outage and working on a fix.

We'd like to find an alternative way to show the Medium posts.

Possible approaches:

| Approach | Pros | Cons |
| --- | --- | -- |
| :white_check_mark: Using Medium [RSS feed](https://medium.com/feed/expedia-group-tech) | Officially supported | There are no explicit "subtitle" or "image" fields, they are buried within the `content:encoded` field in an unstructured way so you need an heuristic to parse it |
| ~~Using Medium [REST API](https://github.com/Medium/medium-api-docs)~~ | | It can only create new user's posts, not get the existing ones |
|Using Medium [GraphQL API](https://medium.com/@mike820324/web-crawler-getting-medium-post-a6e52fd36fd6)| |Unofficial, it's an internal API|

**Comment by giorgiodg** [comment]
You may want to try https://api.rss2json.com as an alternative

**Comment by ffeltrinelli** [comment]
> You may want to try https://api.rss2json.com as an alternative

Thanks for the suggestion! It looks like a valid option, but it has some [payment plans](https://rss2json.com/plans) to consider. The free tier has some limitations, I don't know if it could be enough.

**Comment by ffeltrinelli** [comment]
I tried using the [rss-parser](https://github.com/rbren/rss-parser) library to fetch the RSS feed from the browser and parse the XML into a JSON, but there's another problem:

```
Access to fetch at 'https://medium.com/feed/expedia-group-tech' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

The Medium RSS feed is not setup with a permissive enough CORS policy.

**Comment by ffeltrinelli** [comment]
I'm trying with the approach we already use to get repositories data on the home page:

* fetch data at build time instead of browser's page load. This produces a static json file.
* load the static json file from a React component

WIP is [in this branch](https://github.com/ExpediaGroup/expediagroup.github.io/compare/use-rss-to-get-medium-posts).
