### ISSUE TITLE
Add animated 3D banner

### ISSUE THREAD

**Issue by ffeltrinelli** [ExpediaGroup/expediagroup.github.io#55]
Replace the existing static hero banner with an animated 3D banner using [three.js](threejs.org/) and related libraries.

**Comment by ffeltrinelli** [comment]
Hi @worldtiki @nikos912000 ! These days I was having a look at [three.js](threejs.org/), which is a nice JS library to make 3D graphics on a web browser.

I'm thinking it could be a nice touch to replace the static image-based hero banner we have on the website with a 3D animation. This is a starting point: https://codesandbox.io/s/github/ffeltrinelli/expedia-3d-banner

What do you think about this idea? Suggestions?

**Comment by ffeltrinelli** [comment]
I've added a couple of animated 3D stars, to recall the idea of GitHub starred projects :-)

**Comment by worldtiki** [comment]
Would these be replacing the hero images of each individual project?

**Comment by ffeltrinelli** [comment]
My idea was to replace the hero banner on top of the home page:

<img src="https://user-images.githubusercontent.com/44259532/185678799-378642c0-1cf1-42d7-8676-1d1f2667bb8d.png" width=400/>

**Comment by ffeltrinelli** [comment]
We could also add a water effect and make the text go up and down in the water, like the cube in this example :-D
https://threejs.org/examples/webgl_shaders_ocean.html

**Comment by worldtiki** [comment]
Ok. But lets try to keep the animations subtle.

**Comment by ffeltrinelli** [comment]
Yes, I see what you mean 👍

**Comment by ffeltrinelli** [comment]
This is the result of [my work](https://github.com/ExpediaGroup/expediagroup.github.io/compare/add-3d-banner) so far:

https://user-images.githubusercontent.com/44259532/187042369-9790b74a-15a3-4ff0-82db-1a1610f14630.mp4

Let me know what you think about it!

I have to double check a couple of things:

1. The CPU usage is a bit high, I'll check ways to reduce it. One way is to run the animation for few seconds, then just stop it.
2. The text in the banner is not responsive: it doesn't adapt to the screen width, I've just made it short enough to fit into small devices. I'll check ways to improve this.
